db:
   image: mysql:5.7.20
   restart: always
   ports:
      - 3306:3306
   expose:
      - 3306
   volumes:
     - ./db:/docker-entrypoint-initdb.d
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: loldb

tomcat:
   build: ./web
   restart: always
   links:
     - db:db
   ports:
     - 8080:8080
   expose:
     - 8080