-- MySQL Workbench Synchronization
-- Generated: 2017-11-05 14:41
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Alexandre

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `loldb`.`champion` 
DROP COLUMN `tags`,
DROP COLUMN `blurb`;

ALTER TABLE `loldb`.`item` 
DROP COLUMN `stats`,
DROP COLUMN `gold`,
DROP COLUMN `description`,
ADD COLUMN `tipo` VARCHAR(45) NOT NULL AFTER `image`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
